### register user
POST http://localhost:3000/api/register
Accept: application/json
Content-Type: application/json

{
  "username": "darul ikhsan",
  "email": "darul@gmail.com",
  "password": "darulikhsan"
}

### login user
POST http://localhost:3000/api/login
Accept: application/json
Content-Type: application/json

{
  "username": "Ikhsan",
  "password": "darulikhsan"
}

### create category
POST http://localhost:3000/api/category
Accept: application/json
Content-Type: application/json
API-KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NzY5NDY2MTUsInVzZXJuYW1lIjoiZGFydWwifQ.ptEgTs_xYuYpor_NtSsy3cgPLJapy5ii-o--WLZpXXI

{
  "name" : "Sepatu"
}

### FindById category
GET http://localhost:3000/api/category/1
Accept: application/json
API-KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NzY5NDY2MTUsInVzZXJuYW1lIjoiZGFydWwifQ.ptEgTs_xYuYpor_NtSsy3cgPLJapy5ii-o--WLZpXXI

### create product
POST http://localhost:3000/api/product
Accept: application/json
Content-Type: application/json
API-KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NzY5NDY2MTUsInVzZXJuYW1lIjoiZGFydWwifQ.ptEgTs_xYuYpor_NtSsy3cgPLJapy5ii-o--WLZpXXI

{
  "name" : "Sepatu Nike",
  "category_id" : 1,
  "price" : 1200000
}

### find product by category id
GET http://localhost:3000/api/product/1
Accept: application/json
API-KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NzY5NDY2MTUsInVzZXJuYW1lIjoiZGFydWwifQ.ptEgTs_xYuYpor_NtSsy3cgPLJapy5ii-o--WLZpXXI


### add product to cart
POST http://localhost:3000/api/cart
Accept: application/json
Content-Type: application/json
API-KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NzY5NDY2MTUsInVzZXJuYW1lIjoiZGFydWwifQ.ptEgTs_xYuYpor_NtSsy3cgPLJapy5ii-o--WLZpXXI

{
  "product_id": 1
}

### get list product in cart
GET http://localhost:3000/api/cart
Accept: application/json
API-KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NzY5NDY2MTUsInVzZXJuYW1lIjoiZGFydWwifQ.ptEgTs_xYuYpor_NtSsy3cgPLJapy5ii-o--WLZpXXI

### delete product from cart
DELETE http://localhost:3000/api/cart/2
Accept: application/json
API-KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NzY4OTQ3NzEsInVzZXJuYW1lIjoiSWtoc2FuIn0.liVzDYGsCZjgokOpHJgMfodruFdTig33MdVIoxgWqP8

### checkout product
POST http://localhost:3000/api/transaction
Accept: application/json
Content-Type: application/json
API-KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NzY5NDY2MTUsInVzZXJuYW1lIjoiZGFydWwifQ.ptEgTs_xYuYpor_NtSsy3cgPLJapy5ii-o--WLZpXXI

{
  "user_id": 3,
  "amount": 1000000
}



