### register user
POST http://localhost:3000/api/register
Accept: application/json
Content-Type: application/json

{
  "username": "darul ikhsan",
  "email": "darul@gmail.com",
  "password": "darulikhsan"
}

### login user
POST http://localhost:3000/api/login
Accept: application/json
Content-Type: application/json

{
  "username": "Ikhsan",
  "password": "darulikhsan"
}

### create category
POST http://localhost:3000/api/category
Accept: application/json
Content-Type: application/json
API-KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NzcwMzUzMTAsInVzZXJuYW1lIjoiZGFydWwgaWtoc2FuIn0.Y8xqVJSmQxpejgrStsCXfLiWKiwAaBhHNnoGfAUmRLo

{
  "name" : "Pakaian"
}

### FindById category
GET http://localhost:3000/api/category/4
Accept: application/json
API-KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NzcwMzUzMTAsInVzZXJuYW1lIjoiZGFydWwgaWtoc2FuIn0.Y8xqVJSmQxpejgrStsCXfLiWKiwAaBhHNnoGfAUmRLo

### create product
POST http://localhost:3000/api/product
Accept: application/json
Content-Type: application/json
API-KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NzcwMzUzMTAsInVzZXJuYW1lIjoiZGFydWwgaWtoc2FuIn0.Y8xqVJSmQxpejgrStsCXfLiWKiwAaBhHNnoGfAUmRLo

{
  "name" : "Baju Kaos",
  "category_id" : 2,
  "price" : 50000
}

### find product by category id
GET http://localhost:3000/api/product/7
Accept: application/json
API-KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NzcwMzUzMTAsInVzZXJuYW1lIjoiZGFydWwgaWtoc2FuIn0.Y8xqVJSmQxpejgrStsCXfLiWKiwAaBhHNnoGfAUmRLo


### add product to cart
POST http://localhost:3000/api/cart
Accept: application/json
Content-Type: application/json
API-KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NzcwMzUzMTAsInVzZXJuYW1lIjoiZGFydWwgaWtoc2FuIn0.Y8xqVJSmQxpejgrStsCXfLiWKiwAaBhHNnoGfAUmRLo

{
  "product_id": 2
}

### get list product in cart
GET http://localhost:3000/api/cart
Accept: application/json
API-KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NzcwMzUzMTAsInVzZXJuYW1lIjoiZGFydWwgaWtoc2FuIn0.Y8xqVJSmQxpejgrStsCXfLiWKiwAaBhHNnoGfAUmRLo

### delete product from cart
DELETE http://localhost:3000/api/cart/2
Accept: application/json
API-KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NzY4OTQ3NzEsInVzZXJuYW1lIjoiSWtoc2FuIn0.liVzDYGsCZjgokOpHJgMfodruFdTig33MdVIoxgWqP8

### checkout product
POST http://localhost:3000/api/transaction
Accept: application/json
Content-Type: application/json
API-KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NzcwMzUzMTAsInVzZXJuYW1lIjoiZGFydWwgaWtoc2FuIn0.Y8xqVJSmQxpejgrStsCXfLiWKiwAaBhHNnoGfAUmRLo

{
  "user_id": 3,
  "amount": 10000
}



